# Docker Compose for Deployment
services:
    backend-jap-app:
        container_name: backend-jap-app
        build:
            context: ./backend
            dockerfile: Dockerfile
        command: ["./wait-for-postgres.sh", "db", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
        ports:
            - "8000:8000"
        env_file:
            - ./backend/.env
        networks:
            - jap-network
        depends_on:
            - db
    frontend-jap-app:
        container_name: frontend-jap-app
        build:
            context: ./frontend
            dockerfile: Dockerfile
        ports:
            - "8080:80"
        depends_on:
            - backend-jap-app
        networks:
            - jap-network
    db:
        image: postgres:15-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        env_file:
            - ./backend/.env
        networks:
            - jap-network
        ports:
            - "5432:5432"
    cloudflare:
        container_name: cloudflare-jap-app
        image: cloudflare/cloudflared:latest
        command: ["tunnel", "--no-autoupdate", "run", "--token", "your_token_here"]
        networks:
            - jap-network

networks:
    jap-network:
        driver: bridge

volumes:
    postgres_data: